### ISSUE TITLE
No bars no progress no button press

### ISSUE THREAD

**Issue by N-Kata** [mdnpascual/ToF-Fishing-Bot#3]
![64png](https://user-images.githubusercontent.com/21299150/229324651-ffa50c5a-6370-4946-b37a-7fe5577e332f.png)

tried different coordinates, but still
lik 81 instead of 79 or 117 instead of 115

run as admin turned off AV

**Comment by mdnpascual** [comment]
I have no answer to this. The tool is not detecting anything at all. 

Something is blocking the ability of the tool to screen capture. Cause if it is at least initialized, it should've at least changed the 2 "Label" to 0, and the "Status" to not fishing when u click "Start Fishing".

**Comment by victortron** [comment]
Hi, I'm having a similar issue, however when starting to fish the numbers turn to 0 and it wont do any keyboard input but it does catch the fish whenever its resistance is done. Ive trying changing the values from Y position on the dark places of the bar as you suggested in another issue, but it doesn't seem to work.
Ive recorded the issue here https://streamable.com/mum4b8

**Comment by mdnpascual** [comment]
> Hi, I'm having a similar issue, however when starting to fish the numbers turn to 0 and it wont do any keyboard input but it does catch the fish whenever its resistance is done. Ive trying changing the values from Y position on the dark places of the bar as you suggested in another issue, but it doesn't seem to work. Ive recorded the issue here https://streamable.com/mum4b8

Hi @victortron . Thanks for recording a video. Based on that, the setup for the middle bar is wrong. There is only a 1 PIXEL Difference from both (Upper left Y: 81, Lower right Y: 82). That is not enough Y difference for the tool to detect the middle bar. 

The tool needs at least 5 pixel difference between those 2 values.

**Comment by victortron** [comment]
Trying with 6px difference, it still seems to dont register any keyb input or doesn't seem to detect, I've closed down RTSS and MSI Afterburner just in case it had some issue with those (since it isnt the first time that RTSS interfers with this type of programs) but I cant seem to find anymore workarounds to this issue
![image](https://user-images.githubusercontent.com/73905253/230507120-bd706347-474e-4772-ad1c-cb49a3d28c3b.png)

**Comment by mdnpascual** [comment]
I checked the pixel measurements and it seems correct. It is detecting the fish and player stamina correctly with the green borders on those buttons.
Is ToF running on the monitor that is your main display? I think it is but just double-checking. 

Can you try this build: https://github.com/mdnpascual/ToF-Fishing-Bot/releases/download/1.02-experimental/ToF_Fishing_Bot_v1_0_2_experimental.zip

You can just copy the settings.json on the old build to this new one so you don't need to set it up again

Let me know if it helps

**Comment by victortron** [comment]
Yes it is running on the main display, 
Copying the settingf file, it seems to partially work, it detects the stamina bars correctly but not the progress bar in the center, changing the top left color detection outside the dark bar works, but sometimes fails to track when the fish does this jumping animation
![image](https://user-images.githubusercontent.com/73905253/230516811-2a09c05c-3f75-4293-b280-c356f9f37093.png)
This is with the left bar point selected outside the dark zone, tracking shows as desired but I don't think it should be like that

Edit; I've tested in a couple of fishing spots, including different environments (dark abyss and couple of asperia spots) so far it seems to properly work with the exception I already mentioned about not tracking sometimes when the fish does this little animation. I'll do further testing when I gather more baits, but yeah, bit weird... xD

**Comment by mdnpascual** [comment]
No, having black bars at the top or bottom is definitely wrong. And the tracking will be fucked up when any movements happen on those space.

This is why I suggested to record a video of you fishing legit so you can test it instead on the video so you don't waste baits.

Are you running the game in lower fps? It's weird that the lines aren't straight on the edges and I have a hunch that it's getting confused by that.

For now, I think what I would suggest is manually editing your settings.json. 

Change the values of "UpperLeftBarPoint_Y" and "LowerRightBarPoint_Y". Resetting the tool each time u made a change.

**Increase** the "LowerRightBarPoint_Y" 1 pixel at a time until you see a black bar at the bottom, then revert 1-2 pixels.
Do the same for "UpperLeftBarPoint_Y", Increase it again 1 pixel at a time until the black border at the top is gone.

**Comment by victortron** [comment]
Oops my mistake, I also have a video that I've been using after I ran out of bait, however the issue is that if I correctly set up the pointers it wont detect the bar at all and it wont show like on the video I previously posted on the first comment I posted. Before selecting outside the dark zone the app behaviour with the new experimental version was exactly the same. I've been already moving the values on the settings and it just wont detect anything until its outside the dark zone.

I can keep editing `UpperLeftBarPoint_Y` and `LowerRightBarPoint_Y`, but it wont give me any feedback until `UpperLeftBarPoint_Y` is outside the dark zone, and it doesnt work switching sides; with Left on the dark and Right outside it.

Im running the game at 1920x1080 at 60fps and at Good quality.

**Comment by victortron** [comment]
Ive found the sweetspot for the Y axis on UpperLeftBarPoint_Y and it does seem to work, now the remaining issue is that when selecting both dark zones it wont detect the bar at all. 

Keyboard inputs seem to work fine now since it doesnt expontaneously glitch when the fish jumps anymore.
![image](https://user-images.githubusercontent.com/73905253/230536286-442716ea-d400-4a1a-b3b7-816e47f61b98.png)

**Comment by victortron** [comment]
> No, having black bars at the top or bottom is definitely wrong. And the tracking will be fucked up when any movements happen on those space.
> 
> This is why I suggested to record a video of you fishing legit so you can test it instead on the video so you don't waste baits.
> 
> Are you running the game in lower fps? It's weird that the lines aren't straight on the edges and I have a hunch that it's getting confused by that.
> 
> For now, I think what I would suggest is manually editing your settings.json.
> 
> Change the values of "UpperLeftBarPoint_Y" and "LowerRightBarPoint_Y". Resetting the tool each time u made a change.
> 
> **Increase** the "LowerRightBarPoint_Y" 1 pixel at a time until you see a black bar at the bottom, then revert 1-2 pixels. Do the same for "UpperLeftBarPoint_Y", Increase it again 1 pixel at a time until the black border at the top is gone.

@mdnpascual 
Also I wanted to mention, with the new fishes even at lowest point of FishStaminaBar, the program will think that this stamina bar is over because there is almost no coloring. Since the new alpha fishes can have around 35+, because of how much the bar is divided there tends to be no coloring for the last points (like 1 or 2) ending up in loosing the catch.
If there is a way to add, increase or be able to change the delay between actions on the settings file would be very much appreciated.

**Comment by mdnpascual** [comment]
Making the delay customizable is currently in the works in 2.0

**Comment by mdnpascual** [comment]
Hi @victortron Version 2.0 has been released and the delay you wanted can be customized. Please refer to Advanced Customization >> Delay before capturing fish after fish stamina detected has been depleted on how to do it.

If you have further questions. Please create a new issue.
